### PR TITLE
Detect Cancel Pending Reservation Event in extension_log

### LINKED ISSUE #873: Detect Cancel Pending Reservation Event in Extension Log Table
**Describe the bug**

There is a problem in regards to multiple events being fired when cancelling a pending reservation. As of now, there is no test to cover this part. Specifically, we want to be able to detect when this (cancel pending reservation) event fires. When an event is fired an `Extension.js` script runs. In this case, the script is responsible for logging an API log which is an object published in the context of the extension. If the event has been triggered, we would have to read the appropriate table on the database (`extension_log`). We also have to check that only the events we care about have been fired. For example, we don't have to fire an `EVENT_CREATED` extension when an invoice is generated (i.e. there should only be one record in `extension_log` which is that of the `INVOICE_GENERATION`).

**Expected behavior**

(1) The first expectation is to verify the number of elements in `extension_log` when the Cancel Pending Reservation event is triggered. If 1 then pass, if >1 then fail (with a provided description of why it failed).
(2) The second expectation would be to verify that the element in `extension_log` is specifically `RESERVATION_CANCELLED`.

**Additional context**
(1) The extension should be passed as both sync and async.
(2) It might be the case that we would first have to verify that the `RESERVATION_CANCELLED` log exists before trying to determine what logs should not be present in `extension_log` when cancelling a pending reservation.

### PR DESCRIPTION
**Pull request by MarkBis415**
**Modify** ReservationFlowIntegrationTest to assert that the `RESERVATION_CANCELLED` event is fired when calling `reservationApiV2Controller.cancelPendingReservation`. 
This requires the following to occur:
1. Add the `Extension.js` to `src/test/resources/`
2. Generate the script
- As soon as the test starts, prepare the environment by inserting the extension.js to the database
- Insert as async = true and async = false
3. Check that the particular event has been fired
- We would expect that the corresponding event and only this event logged is `RESERVATION_CANCELLED`

**TODO: 4. Clear the extension log table**
- Use the Spring jdbcTemplate update() method to issue a SQL statement similar to: `TRUNCATE TABLE table_name;` 
- The table is called `extension_log`

**Current behavior**
Presence of `RESERVATION_CANCELLED` log has been asserted. Also, there are always eight rows in the log when we insert two extensions (one async and one sync). The test still fails due to the following:
```
19:56:45.789 [Test worker] WARN  alfio.extension.ScriptingExecutionService - hello from script with event: EVENT_CREATED
19:56:45.883 [pool-4-thread-1] WARN  alfio.extension.ScriptingExecutionService - Was not able to compile script asyncName
org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
…
19:56:46.816 [Test worker] WARN  alfio.extension.ScriptingExecutionService - hello from script with event: EVENT_STATUS_CHANGE
19:56:46.830 [pool-4-thread-1] WARN  alfio.extension.ScriptingExecutionService - Was not able to compile script asyncName
org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
…
19:56:48.825 [Test worker] WARN  alfio.extension.ScriptingExecutionService - hello from script with event: RESERVATION_VALIDATION
19:56:48.825 [Test worker] WARN  alfio.extension.ScriptingExecutionService - Error while executing script syncName:
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
```

On track to close #873.
Contributors: @MarkBis415, @rmace001, @YeeitsAlex

### CODE REVIEW

**Comment by YeeitsAlex** [comment]
Cannot test “cancel pending reservation” because of limitations in the test with running asynchronous extension services. Instead, we have successfully tested an “event created” log, which is a synchronous extension. The next step is to run asynchronous extensions as synchronous during testing. This pull request is ready for review.

File: src/test/resources/extension.js [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+ */
+function executeScript(scriptEvent) {
+    log.warn('hello from script with event: ' + scriptEvent);
+    extensionLogger.logInfo(scriptEvent);//logs into the extension_log table
+    if(scriptEvent === 'INVOICE_GENERATION') {
+	return {
+		invoiceNumber: 'blabla'
+	};
+    }
+}
```
Comment (cbellone) [inline src/test/resources/extension.js]: The test is currently failing because we forgot to add here a "return null;" statement to cover all the other Sync events (like RESERVATION_VALIDATION) that expect the script to return something. So this should be:

```javascript
function executeScript(scriptEvent) {
    log.warn('hello from script with event: ' + scriptEvent);
    extensionLogger.logInfo(scriptEvent);//logs into the extension_log table
    if(scriptEvent === 'INVOICE_GENERATION') {
        return {
            invoiceNumber: 'blabla'
        };
    }
    return null;
}
```
instead

File: src/test/resources/extension.js [hunk 2]
```diff
@@ -35,8 +35,9 @@ function executeScript(scriptEvent) {
...
     extensionLogger.logInfo(scriptEvent);//logs into the extension_log table
     if(scriptEvent === 'INVOICE_GENERATION') {
-	return {
-		invoiceNumber: 'blabla'
-	};
+        return {
+            invoiceNumber: 'blabla'
+        };
     }
+    return null;
```
Comment (rmace001) [inline src/test/resources/extension.js]: Added `return null` here, making this test pass. Thank you for helping us help you! We are ready for the next iteration. 👍

**Comment by cbellone** [comment]
merged. Thanks! :+1:
